# Fedflow config sample
# Fedflow supports the following units:
#   B(b), KB(b), MB(b), GB(b), TB(b)
# In most cases, it is recommended that you use '(K/M/G/T)B' instead of '(K/M/G/T)b', 
# and if the unit is 'B', you can omit it.


# During the running of fedflow, all hard disk reads and writes opertions are in the workdir.
# By default, the workdir is current directory.
workdir: 'res'

debug: false

# You can specify a GPU selection priority, fedflow will use the GPU in the order specified by
#   the priority.
gpu-priority: 
  stratety: 'TOTAL-MEM'  # PCI, TOTAL-MEM, REMAIN-MEM, PERFORMANCE
  reverse: false  # order or reverse order

utilization-limit:  # the maximum utilization of system resources as a percentage
  cpu: 0.8  # average CPU utilization of all logic cpus
  memory: 0.8  # maximum utilization of system memory
  cuda-memory: 0.8  # maximum utilization of every gpu

remain-limit: # the minimum remaining of system resources as a number with unit
  memory: '4GB'
  cuda-memory: '2GB'

task:
  directory-grouping: true
  allow-duplicate-id: true

scheduler:  # some task scheduler parameters
  default-memory: '2GB'
  default-cuda-memory: '2GB'
  auto-adjust: false
  max-waiting: 10
  max-process: 20
  interval: 60  # seconds
  load-nretry: 3
  train-nretry: 3

smtp:
  enable: false
  server-host: 'smtp.example.com'
  server-port: 25
  user: 'user@smtp.example.com'
  password: '******'
  receiver: 'user@smtp.example.com'
  min-interval: 3600 # seconds
  max-numbers: 10
